version: "3.9"
services:
  web:
    build: .
    command: python materialsite/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    env_file:
      - ./.env.dev
    ports:
      - 8000:8000
    depends_on:
      - db
      - maildev

  db:
    image: postgres
    restart: on-failure:5
    env_file:
      - ./.env.dev.db
    volumes:
      - material_site_pg_data:/var/lib/postgresql/data
  
  adminer:
    image: adminer
    restart: on-failure:5
    ports:
      - 8080:8080
    depends_on:
      - db

  maildev:
    image: maildev/maildev
    ports:
      - 1080:1080

volumes:
  material_site_pg_data: