# Generated by Django 4.1.5 on 2023-01-24 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
                ('length', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('width', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('height', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
                ('length', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('width', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('height', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
                ('order_date', models.DateTimeField()),
                ('items', models.ManyToManyField(to='binanalyze.item')),
            ],
        ),
    ]
