# Generated by Django 4.1.5 on 2023-02-07 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitlength', models.CharField(choices=[('in', 'Inch'), ('ft', 'Feet'), ('cm', 'Centimeter'), ('m', 'Meter')], default='cm', max_length=2)),
                ('length', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('width', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('height', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('unitweight', models.CharField(choices=[('lb', 'Pound'), ('g', 'Gram'), ('kg', 'Kilogram')], default='g', max_length=2)),
                ('weight', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitlength', models.CharField(choices=[('in', 'Inch'), ('ft', 'Feet'), ('cm', 'Centimeter'), ('m', 'Meter')], default='cm', max_length=2)),
                ('length', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('width', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('height', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('unitweight', models.CharField(choices=[('lb', 'Pound'), ('g', 'Gram'), ('kg', 'Kilogram')], default='g', max_length=2)),
                ('weight', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShippingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('order_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ShippingOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='binanalyze.item')),
                ('shippingorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='binanalyze.shippingorder')),
            ],
        ),
        migrations.AddField(
            model_name='shippingorder',
            name='items',
            field=models.ManyToManyField(through='binanalyze.ShippingOrderItem', to='binanalyze.item'),
        ),
    ]
