# Generated by Django 4.1.5 on 2023-02-19 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binanalyze', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shippingorderitem',
            constraint=models.UniqueConstraint(fields=('shippingorder', 'item'), name='unique shippingorder item'),
        ),
    ]
