version: "3.9"
services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile_local
    command: python materialsite/manage.py runserver 0.0.0.0:8000
    image: django-lambda-example-web
    volumes:
      - ..:/app
    env_file:
      - ./.env.local
    ports:
      - "8000:8000"
    depends_on:
      - db
      - maildev

  db:
    image: postgres
    restart: on-failure:5
    environment:
      POSTGRES_PASSWORD: pgexamplepassword
    volumes:
      - material_site_pg_data:/var/lib/postgresql/data
  
  adminer:
    image: adminer
    restart: on-failure:5
    ports:
      - 8080:8080
    depends_on:
      - db
  
  maildev:
    image: maildev/maildev
    ports:
      - 1080:1080

volumes:
  material_site_pg_data: